helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView 
from accounts.views import logout_any
from django.conf.urls import handler403

handler403 = 'tickets.views.custom_permission_denied_view'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/logout/", logout_any, name="logout"),
    path("accounts/", include("django.contrib.auth.urls")),  # login/logout/password views
    path("", RedirectView.as_view(pattern_name="tickets:ticket_list", permanent=False)),
    path("tickets/", include("tickets.urls")),
]

tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"
urlpatterns = [
    path("", views.TicketListView.as_view(), name="ticket_list"),
    path("new/", views.TicketCreateView.as_view(), name="ticket_create"),
    path("<int:pk>/", views.TicketDetailView.as_view(), name="ticket_detail"),
    path("<int:pk>/edit/", views.TicketUpdateView.as_view(), name="ticket_update"),
    path("tickets/<int:pk>/delete/", views.TicketDeleteView.as_view(), name="ticket_delete"),
    path("<int:pk>/assign/", views.ticket_assign, name="ticket_assign"),
    path("<int:pk>/close/", views.ticket_close, name="ticket_close"),
    path("<int:pk>/resolve/", views.ticket_resolve, name="ticket_resolve"),
    path("<int:pk>/reopen/", views.ticket_reopen, name="ticket_reopen"),
    path("<int:pk>/comment/", views.add_comment, name="add_comment"),
    path("clients/", views.ClientListView.as_view(), name="client_list"),
    path("clients/new/", views.ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/<int:pk>/edit/", views.ClientUpdateView.as_view(), name="client_update"),
    path("clients/<int:pk>/delete/", views.ClientDeleteView.as_view(), name="client_delete"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("projects/", views.ProjectListView.as_view(), name="project_list"),
    path("projects/new/", views.ProjectCreateView.as_view(), name="project_create"),
    path("projects/<int:pk>/", views.ProjectDetailView.as_view(), name="project_detail"),
    path("projects/<int:pk>/edit/", views.ProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="project_delete"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Helpdesk{% endblock %}</title>
  <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css">
  <script src="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js"></script>


</head>
<body class="container mt-4">
  <nav class="mb-3">
    <a href="{% url 'tickets:dashboard' %}">Acceuil</a> |
    <a href="{% url 'tickets:ticket_list' %}">Tickets</a> |
    <a href="{% url 'tickets:client_list' %}">Clients</a> |
    <a href="{% url 'tickets:project_list' %}">Projets</a> |
    {% if user.is_authenticated %}
      Connecté en tant que {{ user.username }} |
      <a href="{% url 'logout' %}">Déconnexion</a>
    {% else %}
      <a href="{% url 'login' %}">Connexion</a>
    {% endif %}
  </nav>
  {% block content %}{% endblock %}
</body>
</html>